#!/bin/sh

alias dotfiles="git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"

if [ -x "$(command -v nvim)" ]; then
	alias vim="nvim"
fi

if [ -x "$(command -v bat)" ]; then
	alias cat="bat"
fi

alias ..="cd .."
alias ...="cd ../.."
alias repos="cd $HOME/source/repos"

alias ls="ls -F --color=auto"
alias ll="ls -lhA"
alias mkdir="mkdir -pv"

alias cls="clear"
alias trash="mv -v -t $HOME/.trash"
